[package]
name = "agent"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "den-agent"
path = "src/main.rs"

[dependencies]
proto.workspace = true
anyhow.workspace = true
alacritty_terminal.workspace = true
portable-pty.workspace = true
libc.workspace = true
client.workspace = true
smol.workspace = true
serde.workspace = true
serde_json.workspace = true
ignore.workspace = true
notify.workspace = true
trash.workspace = true
grep-regex = "0.1"
grep-searcher = "0.1"
grep-matcher = "0.1"
regex = "1"
url = "2"
dirs.workspace = true
dunce = "1"
tempfile = "3"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation = { version = "0.3", default-features = false, features = ["std", "NSError", "NSFileManager", "NSString", "NSURL"] }
